<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title>Content-Centric Networking in Java: org.ccnx.ccn.test.ThreadAssertionRunner Class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
<link href="tabs.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.5.6 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Packages</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath"><b>org</b>.<b>ccnx</b>.<b>ccn</b>.<a class="el" href="namespaceorg_1_1ccnx_1_1ccn_1_1test.html">test</a>.<a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html">ThreadAssertionRunner</a>
  </div>
</div>
<div class="contents">
<h1>org.ccnx.ccn.test.ThreadAssertionRunner Class Reference</h1><!-- doxytag: class="org::ccnx::ccn::test::ThreadAssertionRunner" -->Junit cannot catch exceptions from spawned threads.  
<a href="#_details">More...</a>
<p>

<p>
<a href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="0a744f71df88409a81b29b82a06d6fca"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::ThreadAssertionRunner" ref="0a744f71df88409a81b29b82a06d6fca" args="(final Runnable runner)" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>ThreadAssertionRunner</b> (final Runnable runner)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="06ae0483b1ba1a739681f3e0e841350c"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::start" ref="06ae0483b1ba1a739681f3e0e841350c" args="()" -->
void&nbsp;</td><td class="memItemRight" valign="bottom"><b>start</b> ()</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="dce4c6710b958cd5e5cdfc84cbff9895"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::join" ref="dce4c6710b958cd5e5cdfc84cbff9895" args="()" -->
void&nbsp;</td><td class="memItemRight" valign="bottom"><b>join</b> ()  throws InterruptedException, Error, Exception </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="af0c4315f866dbc822660a70cad5c1fb"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::isAlive" ref="af0c4315f866dbc822660a70cad5c1fb" args="()" -->
boolean&nbsp;</td><td class="memItemRight" valign="bottom"><b>isAlive</b> ()</td></tr>

</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Junit cannot catch exceptions from spawned threads. 
<p>
This wrapper class will catch assertion failures in a Runnable and report them to the caller.<p>
Junit Assert.X method throw an AssertionError, which is a Throwable -&gt; Error -&gt; AssertionError. So, we capture both an Error and an Exception. Don't use Throwable, as those get messy to handle in the caller.<p>
How to use: 1) Create a Runnable class (could even be anonymous inner class), and wrap it in a <a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html" title="Junit cannot catch exceptions from spawned threads.">ThreadAssertionRunner</a>:<p>
<a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html" title="Junit cannot catch exceptions from spawned threads.">ThreadAssertionRunner</a> tar = new <a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html" title="Junit cannot catch exceptions from spawned threads.">ThreadAssertionRunner</a>(new MyRunner(some_parameter));<p>
2) Start the Runner like a thread:<p>
tar.start();<p>
3) Do normal processing, then stop your runnable. You must join the Runner to wait for exit. THIS STEP IS REQUIRED (it's the join that reports any exceptions or errors from the run() method of your runnable):<p>
tar.join(); <hr>The documentation for this class was generated from the following file:<ul>
<li>src/org/ccnx/ccn/test/ThreadAssertionRunner.java</ul>
</div>
<hr size="1"><address style="text-align: right;"><small>Generated on Wed Sep 14 12:44:32 2011 for Content-Centric Networking in Java by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.5.6 </small></address>
</body>
</html>
